spring.application.name=Actuator
server.port=8097

spring.admin.ui.enabled=true
spring.admin.client.url=http://localhost:8097

admin.login.url=http://localhost:8080/api/admin/login

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=msgmanagementservice@gmail.com
spring.mail.password=grircclbsfyilkcz
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.to=gokulgokul868@gmail.com

