spring:
  application:
    name: profession

  data:
    mongodb:
      uri: mongodb+srv://sadetechnosolutions:oL9rXf6YWECnNgVf@sademondo.rdnxi.mongodb.net/?retryWrites=true&w=majority&appName=sademondo
      database: artist_personal_information

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8099

logging:
  level:
    com.sadetech.profession: INFO
    org.springframework: INFO
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
