spring.application.name=websocket-messaging

server.port=8091

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

#Actuator Configuration
management.endpoints.web.exposure.include= *
management.endpoint.health.show-details=always

spring.boot.admin.client.url=http://localhost:8097
